name: Build Plugin
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore BetterTargetingSystem.sln

      - name: Build Plugin
        run: msbuild BetterTargetingSystem.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BetterTargetingSystem
          path: BetterTargetingSystem/bin/Release/BetterTargetingSystem/
